apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  namespace: {{ template "common.names.namespace" $ }}
  annotations:
    {{- toYaml .Values.kubevirtCR.annotations | nindent 4 }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
    {{- toYaml .Values.kubevirtCR.labels | nindent 4 }}
  name: rfe
spec:
  certificateRotateStrategy:
    selfSigned:
      ca:
        duration: 48h0m0s
        renewBefore: 24h0m0s
      server:
        duration: 24h0m0s
        renewBefore: 12h0m0s
  configuration:
    developerConfiguration:
      featureGates:
      {{- range $feature := .Values.kubevirtCR.featureGates }}
      - {{$feature }}
      {{- end }}     
      useEmulation: {{ $.Values.cnv.debug.useEmulation }}
  customizeComponents: {}
  uninstallStrategy: BlockUninstallIfWorkloadsExist
  workloadUpdateStrategy: {}

