apiVersion: v1
data:
  default-service-account: pipeline
  default-timeout-minutes: {{ .Values.defaultsConfigmap.timeoutMinutes | quote }}
kind: ConfigMap
metadata:
  annotations:
    {{- toYaml .Values.defaultsConfigmap.annotations | nindent 4 }}
  name: config-defaults
  namespace: openshift-pipelines
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}    
