apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  name: patch-operator-{{ template "common.names.fullname" . }}
  namespace: {{ template "common.names.namespace" $ }}
