apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - merge-oauth-identity-providers-job.yaml
  - merge-oauth-identity-providers-role.yaml
  - merge-oauth-identity-providers-role-rolebinding.yaml
  - merge-oauth-identity-providers-role-serviceaccount.yaml

configMapGenerator:
  - name: merge-oauth-identity-providers
    namespace: openshift-config
    files:
      - merge_oauth_identity_providers.py

generatorOptions:
  disableNameSuffixHash: true
