apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rfe-oauth
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - oauths
    verbs:
      - list
      - get
      - patch
      - update
