apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rfe-oauth
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rfe-oauth
subjects:
  - kind: ServiceAccount
    name: rfe-oauth
    namespace: openshift-config
