apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: oauth-patch
  namespace: resource-locker-operator
spec:
  patches:
    - targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: OAuth
        name: cluster
      patchTemplate: |
        spec:
          identityProviders:
            - name: RFE
              mappingMethod: claim
              type: HTPasswd
              htpasswd:
                fileData:
                  name: htpasswd-secret
      id: oauth-patch
      patchType: application/merge-patch+json
