apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rfe-automation-quay
  namespace: quay
rules:
  - apiGroups:
      - "*"
    resources:
      - secrets
    verbs:
      - create
      - patch
      - list
      - update
      - get
  - apiGroups:
      - quay.redhat.com
    resources:
      - quayregistries
    verbs:
      - get
      - list
