apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rfe-automation-quay
  namespace: quay
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rfe-automation-quay
subjects:
  - kind: ServiceAccount
    name: rfe-automation
    namespace: rfe
