apiVersion: redhatgov.io/v1alpha1
kind: Nexus
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
spec:
  persistent: {{ .Values.nexus.persistent.enabled }}
  nexus:
    allowAnonymousAccess: {{ .Values.nexus.allowAnonymousAccess }}
    oauth:
      enabled: {{ .Values.nexus.oauth.enabled }}
      bypassAuthFor: {{- toYaml .Values.nexus.oauth.bypassAuthFor | nindent 8 }}
{{- if .Values.nexus.oauth.adminUsers }}
      adminUsers: {{- toYaml .Values.nexus.oauth.adminUsers | nindent 8 }}
{{- end }}
    resources:
      cpu:
        request: {{ .Values.nexus.resources.requests.cpu | quote }}
        limit: {{ .Values.nexus.resources.limits.cpu | quote }}
      memory:
        request: {{ .Values.nexus.resources.requests.memory | quote }}
        limit: {{ .Values.nexus.resources.limits.memory | quote }}
    expose:
      ssl: {{ .Values.nexus.expose.ssl }}
      kind: {{ .Values.nexus.expose.kind }}
    image:
      src: {{ template "common.images.registryRepository" .Values.nexus.image }}
      tag: {{ .Values.nexus.image.version }}
      pullPolicy: {{ .Values.nexus.persistent.imagePullPolicy }}
    volumeSize: {{ .Values.nexus.persistent.volumeSize }}
