apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-s3-storage
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}