apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nexus-setup
  namespace: rfe
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - get
      - create
