apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nexus-setup
  namespace: rfe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nexus-setup
subjects:
  - kind: ServiceAccount
    name: nexus-setup
    namespace: rfe
