{{- if .Values.groups }}
{{- range $group := .Values.groups }}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: {{ $group.name }}
users:
{{- tpl (toYaml (default list $group.users)) $ | nindent 1 }}
{{- end }}
{{- end }}