apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rfe.oauth.name }}
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
